name: Build

on:
  push:
    branches: [ "main", "master", "develop" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build WGPortal (Bukkit)
        run: mvn clean package --batch-mode --no-transfer-progress

      - name: Build WGPortalVelocity (Velocity)
        run: mvn clean package --batch-mode --no-transfer-progress -f wgportal-velocity/pom.xml

      - name: Upload WGPortal Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WGPortal
          path: target/WGPortal-*.jar
          if-no-files-found: error

      - name: Upload WGPortalVelocity Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WGPortalVelocity
          path: wgportal-velocity/target/WGPortalVelocity-*.jar
          if-no-files-found: error
